services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app            # mount local code into container
    command: flask run --host=0.0.0.0 --port=5000 --reload
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - auth-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 5s
      retries: 10
      timeout: 5s

volumes:
  auth-db-data:
